### ISSUE TITLE
Unhandled ALD files cause xsystem35 error

### ISSUE THREAD

**Issue by nunuhara** [kichikuou/web#3]
When an ALD file contains an unrecognized type character (e.g. "F" in tt2FS.ALD), the function createGr generates an invalid xsystem35.gr file which results in xsystem35 exiting with an error and the game failing to load. This is the error message from xsystem35:

    *ERROR*(sys35_initGameDataResorce): Illigal resouce at line(3) file<xsystem35.gr>

I discovered this when I tried to run the English version of Toushin Toshi II. For some reason, this translation contains a file named "tt2FS.ALD" which triggers this error. This file does not appear to be a valid ALD file, and the game works fine if it is deleted. Still, any user creating a .zip file from the English version would encounter this problem.

**Comment by kichikuou** [comment]
Fixed. Thanks for the report!
