### ISSUE TITLE
音声の再生速度が本来よりも速い

### ISSUE THREAD

**Issue by odoq7211** [kichikuou/web#4]
日本語でのIssue投稿、失礼いたします。
一部環境にて音声の再生速度が約1.088倍速となっており、本来よりも速く再生されています。速度から考えると、44100Hzで生成した波形を48000Hzで再生しているように見受けられます。
当方では以下の環境で問題を確認しました。その他の環境での確認は行っておりませんので、ご了承願います。

| 情報 | 値 |
| :---: | --- |
| OS | Windows 10 Ver. 1909 |
| ブラウザ | Firefox 83.0 (Windows x64) |
| サウンドデバイス | Creative USB Sound Blaster Digital Music Premium HD <br> (48000Hz 16bit) |

お手数をおかけいたしますが、修正を宜しくお願い致します。

**Comment by kichikuou** [comment]
報告ありがとうございます。

ここでの音声というのは、ゲーム中の効果音（BGMではなく）ということで合っていますでしょうか。
また、現象を確認されたゲームのタイトルを教えて下さい。

よろしくお願いします。

**Comment by odoq7211** [comment]
効果音ではなく、FM音源やMIDI音源でのBGMを指します。また、FM音源、MIDI音源のどちらであっても速くなります。
当方で現象を確認した作品は以下の作品になります。

- あゆみちゃん物語
- Rance -光を求めて-
- Rance II -反逆の少女たち-
- あぶないてんぐ伝説
- Dr.STOP!
- DALK
- Dream Program System (D.P.S)
- D.P.S SG (対応ゲーム一覧に未掲載)
- D.P.S SG set2 (対応ゲーム一覧に未掲載)
- D.P.S SG set3 (対応ゲーム一覧に未掲載)
- Super D.P.S (対応ゲーム一覧に未掲載)

これ以外の作品については確認を行っておりませんが、FM音源やMIDI音源を使用する全ての作品にて現象が発生する可能性が高いと考えられます。
また、CD-DAに関してもまだ確認を行っていませんので、こちらは確認次第お伝えさせて頂きます。

**Comment by odoq7211** [comment]
CD-DAについてですが、鬼畜王ランスにて確認を行ったところ正常に再生されておりました。

**Comment by kichikuou** [comment]
ありがとうございます。
ご指摘のとおり、44100Hzで生成したデータを48000Hzで再生してしまっていました。
（私のメイン環境が44100Hzネイティブなので気づきませんでした…）

現在は直っているはずです。キャッシュの関係で初回は修正が反映されないかもしれないので、おかしかったら一旦リロードしてみてください。

**Comment by odoq7211** [comment]
修正を確認しました。
この度はありがとうございました。
