### ISSUE TITLE
対応ゲーム一覧への作品追加について

### ISSUE THREAD

**Issue by odoq7211** [kichikuou/web#5]
日本語でのIssue投稿、失礼いたします。
対応ゲームとして掲載されていない配布フリー宣言対象作品のうち、以下の作品で動作することを確認しました。
- D.P.S SG
- D.P.S SG set2
- D.P.S SG set3
- Super D.P.S 
この4つの作品はアリスソフト アーカイブズ様にて入手できるWindows版イメージのままでは実行できませんが、ZIPファイルを一度展開したのち収録作品ごとに分けてZIP圧縮を行うことで実行可能となります。
プレイまでの手順がやや煩雑となりますが、対応ゲーム一覧への掲載をご検討願います。

**Comment by kichikuou** [comment]
動作確認ありがとうございます。ヘルプページのゲーム一覧に追加しました。

**Comment by odoq7211** [comment]
対応ありがとうございます。
掲載を確認しました。
