### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by kokoiro** [kichikuou/web#8]
Hello there.

I'm building this with some modifications for personal use. I followed the readme and built the files, but after uploading it to my server, the game won't run (just a static black screen), even without modifications. I'm using a simple web server. The page seems to load just fine tho.

Thank you!

**Comment by kichikuou** [comment]
Do you see any error messages in the JavaScript console?

**Comment by kokoiro** [comment]
@kichikuou I was using a friend's CPANEL web server (so I don't have console). Maybe is not compatible?

**Comment by kichikuou** [comment]
I mean, your browser's developer console.
https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools

**Comment by kokoiro** [comment]
@kichikuou Found this:

```
CDDA unlocked [cdda.ts:168:20](/shell/cdda.ts)
wasm streaming compile failed: TypeError: WebAssembly: Response has unsupported MIME type 'application/octet-stream' expected 'application/wasm' [xsystem35.js:1:10784](/loader/xsystem35.js)
falling back to ArrayBuffer instantiation [xsystem35.js:1:10830](/loader/xsystem35.js)
Failed to load<script> origin "/timidity/timidity.js". [en.html:1:1](/loader/en.html)
error { target: script, isTrusted: true, srcElement: script, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, timeStamp: 6497, … }
[shell.ts:25:20](/shell/shell.ts)
Uncaught (in promise) 
error { target: script, isTrusted: true, srcElement: script, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, timeStamp: 6497, … }
​
bubbles: false
​
cancelBubble: false
​
cancelable: false
​
composed: false
​
currentTarget: null
​
defaultPrevented: false
​
eventPhase: 0
​
explicitOriginalTarget: <script src="/timidity/timidity.js">
​
isTrusted: true
​
originalTarget: <script src="/timidity/timidity.js">
​
returnValue: true
​
srcElement: <script src="/timidity/timidity.js">
​
target: <script src="/timidity/timidity.js">
​
timeStamp: 6497
​
type: "error"
​
<get isTrusted()>: function isTrusted()
​
<prototype>: EventPrototype { composedPath: composedPath(), stopPropagation: stopPropagation(), stopImmediatePropagation: stopImmediatePropagation(), … }
```

**Comment by kichikuou** [comment]
Ah, I see. It failed to load the MIDI module. To run a game that use MIDI, one additional set up step is needed. In the `docs` directory, run this command:
```
git clone -b gh-pages https://github.com/kichikuou/timidity.git
```
And try again. I should add this in the doc.

**Comment by kokoiro** [comment]
Working! Thank you!

Another doubt, is there any way to preload the zip file (from server, perhaps?)? I mean, not having to drag the game every time I want to load it.

**Comment by kichikuou** [comment]
That's technically possible (as long as the zip file is on the same server as the web app), but not implemented currently and I have no plan to implement it.

**Comment by kokoiro** [comment]
I see. Would be cool to see it in the future. Thanks for your help!
