### ISSUE TITLE
do you guys have a way to texthook the game 

### ISSUE THREAD

**Issue by atya99** [kichikuou/web#9]
just getting the text from the log automatically pasted into clipboard? would be really useful for me. since rn it only generates log when you click on it

**Comment by kichikuou** [comment]
Personally, I haven't had a need for this kind of functionality, so I'm not entirely sure what specific features you're looking for. Could you please explain in more detail how you would like this to work?

**Comment by atya99** [comment]
Usually, with texthookers, you attach it to a game process, the game text is sent out as a stream, either directly to the clipboard or via a socket connection. This way, each piece of text you see in the game is immediately available for other tools, like a custom HTML page where you can use dictionaries (e.g., Yomitan) to look up words. 

Now as this as a website, traditional texthookers are not an option. I also noticed the backlog text is only generated when you click the log button which is nice but it makes the custom scripts to not get the text value as they appear. If you can somehow make the in-game text "streamable" as they appear, i can use some js scripts to copy it to clipboard as they appear and use dictionaries to look up words easily. 

> Personally, I haven't had a need for this kind of functionality, so I'm not entirely sure what specific features you're looking for. Could you please explain in more detail how you would like this to work?

**Comment by kichikuou** [comment]
Thank you for explaining the background!

I've added a feature to [xsystem35-sdl2](https://github.com/kichikuou/xsystem35-sdl2) (the game engine used by this web app) that automatically copies in-game text to the clipboard as they appear. You can download the latest unreleased version for Windows [here](https://github.com/kichikuou/xsystem35-sdl2/actions/runs/12170483106).

This feature can be enabled from the menu bar by checking `Option` -> `Auto Copy Text to Clipboard`.

Please let me know if this works for you. If not, we might need to explore other ways to make it work with this website.

**Comment by atya99** [comment]
> Thank you for explaining the background!
> 
> I've added a feature to [xsystem35-sdl2](https://github.com/kichikuou/xsystem35-sdl2) (the game engine used by this web app) that automatically copies in-game text to the clipboard as they appear. You can download the latest unreleased version for Windows [here](https://github.com/kichikuou/xsystem35-sdl2/actions/runs/12170483106).
> 
> This feature can be enabled from the menu bar by checking `Option` -> `Auto Copy Text to Clipboard`.
> 
> Please let me know if this works for you. If not, we might need to explore other ways to make it work with this website.

Works perfectly thank you so much. it will help me a ton,
